[package]
name = "crate_roa_server_web"
version = "0.1.0"
authors = ["Sean Lyo <137232774@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
roa = "0.4"
async-std = { version = "1.4", features = ["attributes"] }
