[package]
name = "crate_serde-query_query_for_serde"
version = "0.1.0"
authors = ["slyo <sean.lyo@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde-query = "^0.1"
serde_json = "^1"
serde = { version = "^1", features = ["derive"] }
