[package]
name = "crate_crossbeam_mpmc_channel"
version = "0.1.0"
authors = ["_fy <liuxiaochuan@novogene.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.7.3"
crossbeam-channel = "0.4.0"
