[package]
name = "crate_textwrap_wrap_indent_text"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
textwrap = "^0.14"
