[package]
name = "crate_flamer_calc_time_code_execution"
version = "0.1.0"
authors = ["_fy <liuxiaochuan@novogene.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flamer = "0.2.2"
