[package]
name = "plot"
version = "0.1.0"
authors = ["slyo <sean.lyo@outlook.com>"]
edition = "2018"
description = "https://github.com/38/plotters/tree/master/examples"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
plotters = "^0.3.0"
rand = "0.7.3"
itertools = "0.9.0"
rand_distr = "0.2.2"
criterion = "0.3.2"
rayon = "1.3.0"
rand_xorshift = "0.2.0"
plotters-bitmap = "^0.3.*"
serde_json = "1.0.57"
serde = "1.0.115"
serde_derive = "1.0.115"
num-traits = "0.2.11"
chrono = "0.4.11"
