[package]
name = "crate_lingua_language_detection"
version = "0.1.0"
authors = ["slyo <sean.lyo@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lingua = "^1.0.2"
float-cmp = "^0.8.0"
