[package]
name = "crate_blocking_isolate_io_async"
version = "0.1.0"
authors = ["slyo <sean.lyo@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blocking = "^0.6.0"
futures-lite = "^1.0.0"
